config/routes.rb
Rails.application.routes.draw do

  root to: 'static_pages#home'
  get 'static_pages/help'
  get 'sessions/new'
	get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
	get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  resources :users
  resources :todos do
    member do
        patch :done
        patch :undo
    end
  end
  get '/search' => 'user#search', :as => 'search_user'
  resources :sessions,      only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :user
  default_scope -> { order(date: :desc) }
  validates :user_id, presence: true
  validates :description, presence: { message: "must be given please" }
  validates :date, presence: true
  validates :due_time, presence: true
  validates :status, presence: true

  
  def done?
  	if status == "Done" then
  		return true
  	else
  		return false
  	end
  end
end

app/models/user.rb
class User < ApplicationRecord
	has_many :todos, dependent: :destroy
	before_save { self.email = email.downcase }
	validates :name, presence: true
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true,
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  VALID_PASSWORD_REGEX = /\A(?=.*[a-z])(?=.*\d)[a-z\d]{6,}\Z/
  validates :password, presence: true,
  										format: { with: VALID_PASSWORD_REGEX }

  def feed
  	Todo.where("user_id = ?", id)
  end

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
  def hello
    render html: "hello, world!"
  end
  include SessionsHelper

  private

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
    	log_in user
      redirect_to user
      # Log the user in and redirect to the user's show page.
    else
      flash[:danger] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end

  def destroy
  	log_out
    flash[:success] = "Log out successfully"
  	redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@todo = current_user.todos.build if logged_in?
  end

  def help
  end

  def about
  end

  def contact
  end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :logged_in_user

  # GET /todos
  # GET /todos.json
  def index
    if params[:search]
      @todos = Todo.where(:date => Date.parse(params[:search]))
    else
      @todos = Todo.all
    end
      # @support_histories = current_agent.support_histories.where(:created_at => Date.parse(params[:selected_date]))
  end

  # GET /todo/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = current_user.todos.build(todo_params)

    if @todo.save
      flash[:success] = "Todo created!"
      redirect_to root_url
    else
      render 'static_pages/home'
    end
  end


    
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  def done
    set_todo
    @todo.update_attribute(:status, "Done")
    redirect_to current_user
    # redirect_to @todo, notice: "Todo item completed"
  end

  def undo
    set_todo
    @todo.update_attribute(:status, "Created")
    redirect_to current_user
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    set_todo
    @todo.destroy
    flash[:success] = "Todo delete"
    respond_to do |format|
      format.html { redirect_to current_user, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:date, :due_time, :description, :status)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]

  def index
    @user = User.find(params[:id])
    if params[:search]
      @todos = @user.todos.where(:date => Date.parse(params[:search]))
    else
      @todos = @user.todos.paginate(page: params[:page])
    end
      # @support_histories = current_agent.support_histories.where(:created_at => Date.parse(params[:selected_date]))
  end

  def edit
    @todo = current_user.todos.build if logged_in?
    @user = User.find(params[:id])
  end


  def show
    @user = User.find(params[:id])
    @todos = @user.todos.paginate(page: params[:page])

  end

  def new
  	@user = User.new
  end

  def create
    @user = User.new(user_params)    # Not the final implementation!
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Todo List!"
      redirect_to @user
      # Handle a successful save.
    else
      render 'new'
    end
  end

  def search
    @user = User.find(params[:id])
    # @todos = @user.todos.paginate(page: params[:page])
  end


  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    def correct_user
    	@user = User.find(params[:id])
    	redirect_to(root_url) unless correct_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
    session[:user_id] = user.id
  end

  def signed_in?
    !current_user.nil?
  end
  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token  = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          
          <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                
                
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
     
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_todo_form.html.erb
<%= form_for(@todo) do |f| %>
  
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, placeholder: "Create new todo..." %>

  
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_field :date, min: DateTime.now %>
  </div>
  <div class="field">
  	
    <%= f.label :due_time %><br>
    <% if @todo.due_time.nil?
      @todo.due_time = DateTime.now
      end %>
    <%= f.time_field :due_time, :value => @todo.due_time %>
  </div>
  <%= f.label :status, "Created" %>
  <%= f.radio_button :status, "Created" %>
  <%= f.label :status, "Done" %>
  <%= f.radio_button :status, "Done" %>
 

  <%= f.submit "Post" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to current_user.name, current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.todos.count, "todo") %></span>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
    </aside>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to the Todo List</h1>

    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>

 
<% end %>

app/views/todos/_todo.html.erb
<li>

	<%= todo.date %>
	<%= todo.due_time.strftime("%X") %>
	<%= todo.status %>
	
	<% if current_user?(todo.user) %>
		<%= link_to "delete", todo, method: :delete,
									data: { comfirm: "You sure?"} %>
	<% end %>
	<div class="row clearfix">
		<% if todo.done? %>
			<div class="complete">
				<%= link_to "Done", done_todo_path(todo), method: :patch %>
				<%= link_to "Undo", undo_todo_path(todo), method: :patch %>
			</div>
			<div class="todo_item">
				<p style="opacity: 0.4;"><strike><%= todo.description %></strike></p>
			</div>
			
		<% else %>
			<div class="complete">
				<%= link_to "Done", done_todo_path(todo), method: :patch %>
				<%= link_to "Undo", undo_todo_path(todo), method: :patch %>
			</div>
			<div class="todo_item">
				<p><%= todo.description %></p>
			</div>
		<% end %>
	</div>
</li>

app/views/users/_filter.html.erb
<%= form_for(search_user_path, method: :get) do |form| %>
  <div class="form-group">
    <%= form.label :date %>
    <%= form.date_field :date, min: DateTime.now - 30, max: DateTime.now + 30%>
  </div>
  <%= form.submit "Search", :name => nil %>
<% end %>

app/views/users/edit.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/todo_form' %>
      </section>
    </aside>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to the Todo List</h1>

    <%= link_to "Sign in now!", signin_path, class: "btn btn-lg btn-primary" %>
  </div>

 
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div>
  
	<%= form_for(@user, url: signup_path) do |f| %>
	  <%= render 'shared/error_messages', object: f.object %>
	  <%= f.label :name %>
	  <%= f.text_field :name, class: 'form-control' %>

	  <%= f.label :email %>
	  <%= f.email_field :email, class: 'form-control' %>

	  <%= f.label :password %>
	  <%= f.password_field :password, class: 'form-control' %>

	  <%= f.label :password_confirmation, "Confirmation" %>
	  <%= f.password_field :password_confirmation, class: 'form-control' %>

	  <%= f.submit "Create my account", class: "btn btn-primary" %>
	<% end %>

</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        
        <%= @user.name %>
      </h1>
    </section>
  </aside>

  <%= render 'filter' %>

  <div class="col-md-8">
    <% if @user.todos.any? %>
      <h3>Todo List (<%= @user.todos.count %>)</h3>
      <ol>
        <%= render @todos %>
      </ol>
      
    <% end %>
  </div>
  <%= link_to 'New Todo List', edit_user_path %>
</div>